### ISSUE TITLE
No motd messages after 3.10.3 update

### ISSUE THREAD

**Issue by Robbyts** [WordOps/WordOps#204] opened 2019-11-18 06:51 UTC
No motd messages after 3.10.3 update. Can't see landscape-sysinfo, livepatch, updates-available, etc. messages at ssh login. 

System Information

- [Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic ] `lsb_release -a`
- [ NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (7.2.24-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

PHP (7.3.11-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

MySQL (10.4.10-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             7
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf] `wo info`
- [ ] `nginx -V`
- [ ] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

**Comment by VirtuBox** [comment] 2019-11-18 09:11
Hello @Robbyts,
thanks for your report, I have found the cause of this issue and pushed a fix with commit bab3419fcb13d69c8cd5159f5c98711a2380580a, it will be available in the next release

**Closed** 2019-12-03 20:44 UTC
Labels: Fix available in next release
