### ISSUE TITLE
`sudo wo site create` Taking Infinite time

### ISSUE THREAD

**Issue by arihantchopra** [WordOps/WordOps#624] opened 2024-03-05 05:31 UTC
I have 2 dedicated server with ubuntu 22.04 having 32 Cores & 64GB and 128GB of RAM repectively. I am facing an strange issue since last month that whenever i am trying to create a new website using "sudo wo site create example.com --php81" it just stuck at below output and takes Infinite time to create the site. Some time it takes an hours and someday it takes 4-5 hours to create a site. 

Command : 
sudo wo site create example.com --php81
Output :
Running pre-update checks       [OK]
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]

I already updated the wo stack but that too didn't helped me.

**Comment by arihantchopra** [comment] 2024-03-05 14:35
Yes please let me know if any info is required. 
I want to correct one thing that on one server OS is : Ubuntu 20.04.6 LTS

**Comment by VirtuBox** [comment] 2024-04-06 00:31
I have found the cause of the issue. WordOps is looking for broken symlink in /var/www, so if you have a lot of files, it could require a long time. I'm working on a fix.

**Comment by arihantchopra** [comment] 2024-04-06 06:40
@VirtuBox is there any temporary workaround?

**Comment by VirtuBox** [comment] 2024-04-21 15:33
Hello @arihantchopra,
No sorry, I'm working on it and a fix should be available very soon.

**Comment by VirtuBox** [comment] 2024-04-21 20:49
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`

**Closed** 2024-04-21 23:56 UTC
Labels: bug, In progress, investigating

**Comment by arihantchopra** [comment] 2024-04-29 06:04
Now stuck at below for more than an hour : 

root@Ubuntu-2004-focal-64-minimal ~ # sudo wo update
Downloading update script        [Done]
updating WordOps, please wait...

Welcome to WordOps install/update script v3.20.0

Installing wo dependencies      [OK]
Installing WordOps      [OK]
Running post-install steps
