### ISSUE TITLE
Is OpenLiteSpeed an option?

### ISSUE THREAD

**Issue by michacassola** [WordOps/WordOps#301] opened 2020-06-30 16:28 UTC
I just read this article here: https://wpspeedmatters.com/openlitespeed-vs-nginx-in-wordpress/
Should OpenLiteSpeed be considered?

Advantages over NGINX:
 - Apparently slightly better than NGINX
 - Apache-Drop-In meaning .htaccess functionality will work

**Comment by juanpvh** [comment] 2020-08-02 01:26
These tests are very strange.
I did my own test. The tests were on real wordpress sites, a site with many javascripts (google ads, adsense, facebook, chatbot, analitycs). The results between Nginx and Openlitespeed were almost the same. The test was between wordOps vs Cyberpanel.
The winner for me was of course wordOps, I use nginx the longest.

now openlitespeed + node.js + ghost this stack has excellent compatibility, having a very high result.

**Comment by kymc** [comment] 2020-08-07 05:28
Duplicate of #224

**Comment by VirtuBox** [comment] 2020-08-07 11:44
I'm closing this issue to only keep the previous one (#224).

**Closed by VirtuBox** 2020-08-07 11:44 UTC
Labels: duplicate
