### ISSUE TITLE
Cannot install Wordops anymore

### ISSUE THREAD

**Issue by jazir555** [WordOps/WordOps#623] opened 2024-03-03 11:16 UTC
This is happening all of a sudden on both debian and ubuntu when trying to run "wo stack install". Site creation also fails now.

Error message:

Traceback (most recent call last):.]
  File "/opt/wo/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/wo/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/wo/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/opt/wo/lib/python3.11/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/opt/wo/lib/python3.11/site-packages/urllib3/connection.py", line 238, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe0e77b7290>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/wo/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='v4.wordops.eu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0e77b7290>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
           ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
           ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/stack.py", line 515, in install
    post_pref(self, apt_packages, [])
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/stack_pref.py", line 407, in post_pref
    server_ip = requests.get('http://v4.wordops.eu')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='v4.wordops.eu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0e77b7290>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by angelosleebos** [comment] 2024-03-03 20:10
I am getting the same error on both ubuntu, debian servers

**Comment by vikas5914** [comment] 2024-03-03 21:40
The issue is with WoordOps. You will get errors for all OS. 

So wait until @VirtuBox fixes this.

**Comment by VirtuBox** [comment] 2024-03-03 22:30
Issue has been fixed, sorry for the delay

**Comment by VirtuBox** [comment] 2024-04-06 00:32
A stable fix for this issue will be available soon.

**Comment by VirtuBox** [comment] 2024-04-21 20:49
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`

**Closed by VirtuBox** 2024-04-21 20:49 UTC
Labels: In progress, Fix available in next release
