### ISSUE TITLE
www is added to subdomain.

### ISSUE THREAD

**Issue by mardoqueo** [WordOps/WordOps#178] opened 2019-10-11 22:41 UTC
Hi, when `wo site create prueba.buylatam.club --wp -le --php73` browser adds `www.` before `prueba.buylatam.club`.
`A record` working flawlessly.

Before updating to latest WO I managed to create severarl WP subdomains in same server.

Tried `--wpsubdomain` and still I get `www.` before subdomain.
I get to the login page, but without CSS and instead of logging in it takes me to the root website, also tried different subdomains and it just doesn't work.

> Initially posted in https://community.wordops.net/d/190-subdomain-gets-added-www

System Information:
- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

<details>
  <summary>wo info</summary>
NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (7.2.22-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172
While reading from '/etc/php/7.3/fpm/pool.d/www.conf' [line 24]: option 'php_admin_value[open_basedir]' in section 'www' already exists

</details>

<details>
  <summary>nginx -V</summary>
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1c  28 May 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-4BKPhS/nginx-1.16.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/nginx-echo --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/memc-nginx-module --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/HttpRedisModule --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/nginx-module-vts --add-module=/build/nginx-4BKPhS/nginx-1.16.1/debian/modules/ngx_brotli

</details>

- [ ] `wo -v`
WordOps v3.9.8.11
Copyright (c) 2019 WordOps.

- [ ] `wp cli info --allow-root`
OS:	Linux 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.3
PHP version:	7.3.9-1+ubuntu19.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.3/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.3.0

- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`
Here the link to provide in your github issue : https://transfer.sh/hu8nQ/wordops.tar.gz

**Comment by VirtuBox** [comment] 2019-10-12 08:53
Hello @mardoqueo,
thanks for your report. I already found the cause of this issue and it will be fixed in the next release.

**Comment by mardoqueo** [comment] 2019-10-12 12:00
Thanks Virt!

**Closed** 2019-10-15 14:39 UTC
Labels: Fix available in next release
