### ISSUE TITLE
Debian 10 Buster Mariadb 10.5

### ISSUE THREAD

**Issue by mscice** [WordOps/WordOps#343] opened 2020-11-10 09:39 UTC
Hello, I see that default install of wordops is 10.3 mariadb... what would be the process upgrading it to 10.5.. 

Are there any issues running 10.5 with wordops?

Thank you

**Comment by VirtuBox** [comment] 2020-11-10 13:06
Hello @mscice,
since the release v3.13.0, WordOps install MariaDB 10.5 by default.
If you already have MariaDB 10.3 installed, you can upgrade to MariaDB 10.5 with the command `wo stack migrate --mariadb`.

**Comment by TuaVida** [comment] 2020-11-17 15:42
Hello VirtuBox,

I face problems when trying to upgrade to MariaDB 10.5.
When I use the wo stack migrate --mariadb command, I just get the error below:

`Incorrect parameters
Usage :
zstd [args] [FILE(s)] [-o file]

FILE : a filename
with no FILE, or when FILE is - , read standard input
Arguments :
-# : # compression level (1-19, default:3)
-d : decompression
-D file: use file as Dictionary
-o file: result stored into file (only if 1 input file)
-f : overwrite output without prompting
--rm : remove source file(s) after successful de/compression
-k : preserve source file(s) (default)
-h/-H : display help/long help and exit
mysqldump: Got errno 32 on write`

I've tried to correct this error, but to no avail.
Is there a problem with updating WordOps and leaving MariaDB at a lower version than 10.5?

Thanks.

**Comment by jeroenops** [comment] 2020-12-10 14:55
Are you using Debian or Ubuntu? And which version? Also, are there some more technical details in the WordOps log (`/var/log/wo/wordops.log`)?

**Comment by mscice** [comment] 2020-12-10 15:06
issue fixed

**Comment by Slapbox** [comment] 2020-12-19 21:25
@mscice could you share how you resolve this? We're seeing the exact issue same.

@jeroenops any ideas? I couldn't find anything that seemed helpful in that log file. We're on Debian 9 All it shows is:


```bash
Command Error: ^[[0m
^[[32m2020-12-19 21:18:44,692 (INFO) wo : ^[[94mIf your database size is big, migration may take some time.^[[0m
^[[32m2020-12-19 21:18:44,692 (INFO) wo : ^[[94mDuring migration non nginx-cached parts of your site may remain down^[[0m
^[[32m2020-12-19 21:18:46,307 (INFO) wo : ^[[94mBacking up database at location: /var/lib/wo-backup/mysql^[[0m
^[[36m2020-12-19 21:18:46,308 (DEBUG) wo.core.logging : ^[[95mCreating directory/var/lib/wo-backup/mysql^[[0m
^[[32m2020-12-19 21:18:46,309 (INFO) wo : ^[[94mBacking up all databases^[[0m
^[[31m2020-12-19 21:18:46,336 (ERROR) wo : ^[[91mmysqldump: Got errno 32 on write
^[[0m
```

**Comment by mscice** [comment] 2020-12-20 07:53
Did you wo update?

is that directory writable? You doing this as root?

**Comment by Slapbox** [comment] 2020-12-20 20:11
Thanks for your reply @mscice.

- Yes we ran `wo update` to 3.13.2. We didn't try migrating to MariaDB 10.5 until 3.13.2 was released, so any bugs in earlier versions of 3.13.x shouldn't be a factor.
- Is the directory writeable? Yes - and I even tried using `chmod 777` to temporarily open it open completely
- Yes, running as root

**Comment by Slapbox** [comment] 2020-12-20 20:17
@VirtuBox if all else fails, is there a way to disable the backup feature and force the migration? Between manually created backups and virtual machine snapshots, there's plenty of other safety nets we can fall back on.

**Comment by Slapbox** [comment] 2020-12-20 20:38
I tried everything mentioned here: https://stackoverflow.com/a/30460073/6025788

I didn't run into any issues in those steps. I increased `max_allowed_packet` to `1G` from the default of `64M` in our `my.cnf` file. We have almost 4gb of space available and the combined size of our databases is approximately 150mb. Any ideas?"

**Comment by mscice** [comment] 2020-12-20 22:52
hmm i have no clue, did you restart mysql? reinstall gzip? check permissions?

user full path for backup

**Comment by Slapbox** [comment] 2020-12-20 23:38
Yeah it's a weird one! I kept thinking, "Surely this will fix it!" - but sadly not.

It occurred to me to try using the full path in the backup command since that was a common suggestion, but I don't have control over that as far as I can tell.

**Additional steps taken:**

- Updated/upgraded/dist-upgraded with apt
- Restarted mysql
- Disabled all custom entries in our mysql's my.cnf file
- Server restart

I didn't reinstall gzip since I felt confident it was working after testing.

Is there something I should check the permissions of besides the backup folder that WordOps tries to write to?

**Comment by mscice** [comment] 2020-12-20 23:48
You running it as root? Di you wo stack restart ?

Try export LANG=C

**Comment by Slapbox** [comment] 2020-12-30 20:44
Got a chance to try `export LANG=C` but unfortunately the outcome is the same. Running as root and tried `wo stack restart` as well as a full server reboot.

**Comment by Slapbox** [comment] 2021-01-04 20:44
@jeroenops @jeroenlaylo @VirtuBox any ideas about this?

**Comment by jeroenops** [comment] 2021-01-04 21:14
**How is your server partitioned?**

I am asking this, because error 32 means a broken pipe. In the majority of the cases, this is caused by insufficient diskspace - or because a command was terminated before actually finishing the job. Although `Incorrect parameters` on `zstd` could indicate a different problem.

Does the backup error out fairly quickly?

**Comment by Slapbox** [comment] 2021-01-04 22:30
Hey @jeroenops, thanks for your reply!

**As far as partitions**, we're using the default filesystem partitioning for a Debian virtual machine from Digital Ocean - all of our data is on `/dev/vda1`, with some other auto-created partitions using `udev` and `tmpfs` - none of which are full either.

**The backup errors out almost instantly**. I figured it was a space thing at first and cleared more and more space, but unless the backups require 20x the space of the databases, I now feel confident that can't be the cause.

**As for those commands, here are the outputs:**

```bash
[~] wo -v
WordOps v3.13.2
Copyright (c) 2020 WordOps.

[~] lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

[~] zstd -V
*** zstd command line interface 64-bits v1.1.2, by Yann Collet ***

```

**Comment by jeroenops** [comment] 2021-01-05 08:52
**Thank you @Slapbox for the elaborate reply!**

My suspicion is that you have an incompatible version of `zstd`. The `-T0` argument [doesn't work with all versions](http://manpages.org/zstd). Since I do not have access to a Debian 9 machine and a lack of time that doesn't allow me to install a VM with it, could you issue `man zstd` and look whether the `-T` argument is in there?

If it isn't, the fastest route down would be to install/update to a version that supports this argument. @VirtuBox I'll check whether this goes for Debian 9 in general later this week, if it does, the fix is fairly simple in `wo/core/mysql.py` it seems.

**Comment by Slapbox** [comment] 2021-01-05 22:05
@jeroenops indeed `-T` is an invalid parameter with this version of `zstd` (1.1.2)

I'm always cautious about upgrading anything that's included in the distro, [as `zstd@1.1.2` is in Debian 9](https://packages.debian.org/stretch/zstd). 

[There's a backport](https://packages.debian.org/stretch-backports/zstd) for `zstd@1.3.8`, though I've not dabbled with backports before and I'm not 100% sure that version supports the `-T` parameter, although presumably it does since @mscice was able to get things working on Debian 10.

**Comment by jeroenops** [comment] 2021-01-06 09:39
If you are feeling adventurious, you could take out the `-T` parameter in `wo/core/mysql.py` to temporary resolve the issue. If you are willing to go down this path, make sure you backup the original `mysql.py` to be able to throw it back before a WO update.

However, this should need a bit more investigating and depending the outcome, fixing in WordOps itself.

**Comment by Slapbox** [comment] 2021-01-07 19:55
Considering the phenomenal performance WordOps already offers, I think I can hold off until the issue is fixed in WordOps itself.

But if I can be of any help in reaching a final resolution, let me know, I'll be happy to help!

**Comment by VirtuBox** [comment] 2021-01-08 12:14
> @jeroenops indeed `-T` is an invalid parameter with this version of `zstd` (1.1.2)
> 
> I'm always cautious about upgrading anything that's included in the distro, [as `zstd@1.1.2` is in Debian 9](https://packages.debian.org/stretch/zstd).
> 
> [There's a backport](https://packages.debian.org/stretch-backports/zstd) for `zstd@1.3.8`, though I've not dabbled with backports before and I'm not 100% sure that version supports the `-T` parameter, although presumably it does since @mscice was able to get things working on Debian 10.

Hello @Slapbox,
thanks for your report. I will fix this issue asap.

**Comment by Slapbox** [comment] 2021-03-08 20:47
Any update on this issue? 

I manually removed `-T0`, ran the upgrade, and then reverted the file and everything seems good.

**Comment by VirtuBox** [comment] 2022-10-24 15:03
packages.sury.org/php](https://packages.sury.org/php/) provide an up to date release of zstd and it fix this issue.

**Closed by VirtuBox** 2022-10-24 15:03 UTC
Labels: question
